# File located in /home/docker-lab
# Docker compose images were pulled from official documentation and adjusted as needed

services:
  prometheus:
    image: prom/prometheus
    restart: 'unless-stopped'
    ports:
      - "9090:9090" # Expose the port
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml # Path to the config file
      - prometheus_data:/prometheus # For persistent storage
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    restart: 'unless-stopped'
    ports:
      - "3000:3000" # Port for Grafana UI
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  portainer:
    image: portainer/portainer-ce
    restart: 'unless-stopped'
    ports:
      - "9000:9000" # Port for Portainer UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # To manage Docker
      - portainer_data:/data

  node-exporter:
    image: prom/node-exporter:latest
    restart: 'unless-stopped'
    ports:
      - "9100:9100" # Port for Node metrics
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude="^/(sys|proc|dev|host|etc)($|/)"'

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: 'unless-stopped'
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
    environment:
      TZ: 'US/Central'
      FTLCONF_webserver_api_password: '553Cr-tch991'
      FTLCONF_dns_listeningMode: 'ALL' # If using Docker's default `bridge` network setting the dns listening mode should be set to 'ALL' ; allows devices to connect
      PIHOLE_DNS: 1.1.1.1;1.0.0.1 # Tells Pi-hole where to resolve domains; this is CloudFlare's DNS
    volumes:
      - './etc-pihole:/etc/pihole' # For persisting Pi-hole's databases and common configuration file
    dns: # CloudFlare's DNS
      - 1.1.1.1
      - 1.0.0.1

  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: 'unless-stopped'
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - /docker-lab/jellyfin/config:/config
      - /docker-lab/jellyfin/cache:/cache
      - type: bind
        source: /raid1/archive/jellyfin
        target: /media
        read_only: true
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  

volumes:
  prometheus_data:
  grafana_data:
  portainer_data:

